config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :singers
  resources :albums
  resources :artists
  resources :genres
  resources :clients, only: [:index]
  resources :payments, only: [:index] 
  resources :songs do
    member do
      get 'duration'
    end
  end
  devise_for :users
  root to: "dashboard#index"

  resources :dashboard, only: [:index] do 
    collection do
      get :client_chart
      get :payment_chart
      get :status_chart
    end 
  end
  namespace :api, defaults: { format: :json } do
    post 'login', to: 'auth#login'
    post 'google_oauth2', to: 'auth#google_oauth2'

    resources :singers, only: [:index, :show] do 
      collection do
        get 'albums'
      end
    end
    resources :genres, only: [:index, :show] do
      member do
        get :albums
        get :related
      end
    end
    resources :authors, only: [:index, :create, :show]
    resources :albums, only: [:index, :create, :show] do
      member do
        get :related
      end
    end
    resources :songs, only: [:index, :create, :show] do 
      resources :comments, only: [:index]
    end

    resources :comments, only: [:show]    

    namespace :me do
      resources :rooms, only: [:index, :create, :destroy] do
        member do
          get :songs
        end
      end

      resources :invitations, only: [:index, :create, :show]
      resources :suggest, only: [:index, :create]
      resources :albums, only: [:index, :create, :show, :destroy, :update] do
        member do
          post 'add_song_ids'
          post 'remove_song_ids'
          post :songs
        end
      end
      resources :histories, only: [:index, :create]
      resources :likes, only: [:index, :create] do
        collection do
          delete 'destroys'
        end
      end
      get 'search'
      resources :follows, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
    end

    resources :me, only: [:index]
    post '/create-checkout-session', to: 'payments#create_checkout_session'
    post '/create-checkout-submission', to: 'payments#create_checkout_submission'
    resources :stripe_webhooks, only: [:create]
  end

  match '*path', to: 'api/application#options', via: :options

end

app/models/genre.rb
class Genre < ApplicationRecord
  attr_accessor :logo

  has_many :songs, dependent: :nullify
  has_many :albums, dependent: :nullify

  before_destroy :cleanup_associated_records

  private

  def cleanup_associated_records
    self.songs.update_all(genre_id: nil)
    self.albums.update_all(genre_id: nil)
  end

end

app/controllers/api/genres_controller.rb
class Api::GenresController < Api::ApplicationController
    def index
      page_size = params[:page_size] || 10
      genres = Genre.all.page(params[:page]).per(page_size)
      render json: {
        genres: ActiveModel::Serializer::CollectionSerializer.new(genres, each_serializer: GenreSerializer,is_song: false),
        total_pages: genres.total_pages
      }
    end
  
    def show 
      genre = Genre.find(params[:id])
      render json: genre, each_serializer: GenreSerializer, is_song: true
    end

    def albums 
      genre = Genre.find(params[:id])
      albums = genre.albums
      render json: albums, each_serializer: AlbumSerializer, is_song: true
    end

    def related
      genre = Genre.find(params[:id])
      genres = Genre.where.not(id: genre.id).limit(3)
      render json: genres, each_serializer: GenreSerializer, is_song: false
    end
  
  end
  

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all.page(params[:page]).per(8)
  end

  # GET /genres/1 or /genres/1.json
  def show
    @albums = @genre.albums
    @songs = @genre.songs
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        if genre_params['logo']
          url = CloudinaryService.upload_image(genre_params['logo'])
          @genre.update(image: url)
        end
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        if genre_params['logo']
          url = CloudinaryService.upload_image(genre_params['logo'])
          @genre.update(image: url)
        end
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:title, :description, :logo)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<div class="row justify-content-center">
  <%= form_with(model: genre) do |form| %>
    <% if genre.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

        <ul>
          <% genre.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-12 col-md-6">

        <div class="form-group">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :logo, "Logo", class: "form-label" %>
          <%= form.file_field :logo, class: "form-control" %>
        </div>
      </div>

      <div class="col-12">

        <div class="form-group">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

      </div>
    </div>
    <div class="actions mb-3">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/genres/edit.html.erb
<div class="container-fluid">

<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

</div>

app/views/genres/index.html.erb
<div class="container-fluid"> <h1 class="mt-4">Genres</h1> </div>
<div class="container-fluid d-flex justify-content-end mb-3">
  <%= link_to 'New Genre', new_genre_path, class: "btn btn-primary" %>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-lg list-group-flush list my-n4">
            <% @genres.each do |genre| %>
              <li class="list-group-item">
                <div class="row align-items-center">
                  <div class="col col-2">
                    <% if genre.image.present? %>
                      <%= link_to genre_path(genre) do %>
                        <%= image_tag genre.image, alt: "image", size: "160x120" %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="col">
                    <h4 class="mb-1 name">
                      <%= link_to genre_path(genre) do %> 
                        <%= genre.title %>
                      <% end %>
                    </h4>
                    <p class="card-text small text-body-secondary">
                      <%= genre.description %>
                    </p>

                  </div>
                  <div class="col-auto">
                    <%= link_to 'Show', genre_path(genre), class: "btn btn-sm btn-primary d-none d-md-inline-block" %>
                    <%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-primary d-none d-md-inline-block" %>
                  </div>
                </div> 
              </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <%= paginate @genres, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/genres/new.html.erb
<div class="container-fluid">

<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

</div>

app/views/genres/show.html.erb
<div class="header">
<div class="container-fluid mt-3">
  <div class="header-body">
    <div class="row align-items-end">
      <div class="col">
        <h1 class="header-title">
          <%= @genre.title %>
          <%= link_to edit_genre_path(@genre) do %>
            <i class="mx-2 fa fa-edit"></i> 
          <% end %>
        </h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">  </div>
      <% if @genre.image.present? %>
        <%= link_to edit_genre_path(@genre) do %>
          <%= image_tag @genre.image, alt: "image", size: "485x325" %>
        <% end %>
      <% end %>

      <p class="mt-3">
        <h3>Description:</h3>
        <p><%= @genre.description %></p>
      </p>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <!-- Projects -->
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">
            Danh sách albums của <%=  @genre.title %>
          </h4>
          <%= link_to 'New album', new_album_path(genre_id: @genre.id), class: "btn btn-sm btn-primary" %>
        </div>
        <div class="table-responsive mb-0" data-list='{"valueNames": ["project-project", "project-status", "project-progress", "project-date"]}'>
          <table class="table table-sm table-nowrap card-table table-hover">
            <thead>
              <tr>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-project">
                    Logo
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-status">
                    Title
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-progress">
                    Create date
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort text-center" data-sort="project-date">
                    Number song 
                  </a>
                </th>
              </tr>
            </thead>
            <tbody class="list">
            <% @albums.each do |album| %>
              <tr>
                <td class="project-project">
                  <h4 class="fw-normal mb-1">
                    <% if album.image.present? %>
                      <%= link_to album_path(album) do %>
                        <%= image_tag album.image, alt: "image", size: "50x150" %>
                      <% end %>
                    <% end %>
                  </h4> 
                </td>
                <td class="project-status">
                  <%= link_to "#{album.title}", album_path(album) %>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= album.created_at&.strftime("%d/%m/%Y") %>
                  </div>
                </td>
                <td class="project-date">
                  <div class="d-flex mx-5">
                    <%= album.songs.size %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div> 
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <!-- Projects -->
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">
            Danh sách nhạc của <%=  @genre.title %>
          </h4>
          <%= link_to 'New song', new_song_path(genre_id: @genre.id), class: "btn btn-sm btn-primary" %>
        </div>
        <div class="table-responsive mb-0" data-list='{"valueNames": ["project-project", "project-status", "project-progress", "project-date"]}'>
          <table class="table table-sm table-nowrap card-table table-hover">
            <thead>
              <tr>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-project">
                    Logo
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-status">
                    Title
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-progress">
                    View
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort text-center" data-sort="project-date">
                    Create date
                  </a>
                </th>
              </tr>
            </thead>
            <tbody class="list">
            <% @songs.each do |song| %>
              <tr>
                <td class="project-project">
                  <% if song.image.present? %>
                    <%= link_to song_path(song) do %>
                      <%= image_tag song.image, alt: "image",  size: "300x150" %>
                    <% end %>
                  <% end %>
                </td>
                <td class="project-status">
                  <%= link_to "#{song.title}", song_path(song) %>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= song.views %>
                  </div>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= song.created_at&.strftime("%d/%m/%Y") %>
                  </div>
                </td>

                <td class="project-project">
                  <h4 class="fw-normal mb-1">
                    <% if song.audio.present? %>
                      <audio controls>
                        <source src="<%= song.audio %>" type="audio/mpeg">
                      </audio>                   
                    <% end %>
                  </h4> 
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div> 
</div>