config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :singers
  resources :albums
  resources :artists
  resources :genres
  resources :clients, only: [:index]
  resources :payments, only: [:index] 
  resources :songs do
    member do
      get 'duration'
    end
  end
  devise_for :users
  root to: "dashboard#index"

  resources :dashboard, only: [:index] do 
    collection do
      get :client_chart
      get :payment_chart
      get :status_chart
    end 
  end
  namespace :api, defaults: { format: :json } do
    post 'login', to: 'auth#login'
    post 'google_oauth2', to: 'auth#google_oauth2'

    resources :singers, only: [:index, :show] do 
      collection do
        get 'albums'
      end
    end
    resources :genres, only: [:index, :show] do
      member do
        get :albums
        get :related
      end
    end
    resources :authors, only: [:index, :create, :show]
    resources :albums, only: [:index, :create, :show] do
      member do
        get :related
      end
    end
    resources :songs, only: [:index, :create, :show] do 
      resources :comments, only: [:index]
    end

    resources :comments, only: [:show]    

    namespace :me do
      resources :rooms, only: [:index, :create, :destroy] do
        member do
          get :songs
        end
      end

      resources :invitations, only: [:index, :create, :show]
      resources :suggest, only: [:index, :create]
      resources :albums, only: [:index, :create, :show, :destroy, :update] do
        member do
          post 'add_song_ids'
          post 'remove_song_ids'
          post :songs
        end
      end
      resources :histories, only: [:index, :create]
      resources :likes, only: [:index, :create] do
        collection do
          delete 'destroys'
        end
      end
      get 'search'
      resources :follows, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
    end

    resources :me, only: [:index]
    post '/create-checkout-session', to: 'payments#create_checkout_session'
    post '/create-checkout-submission', to: 'payments#create_checkout_submission'
    resources :stripe_webhooks, only: [:create]
  end

  match '*path', to: 'api/application#options', via: :options

end

app/models/artist.rb
class Artist < ApplicationRecord
  attr_accessor :avatar

  has_many :artist_songs, dependent: :destroy
  has_many :songs, through: :artist_songs
  has_many :albums, dependent: :destroy

  has_many :follows, dependent: :destroy
  has_many :users, through: :follows

  enum tag: { author: "author", singer: "singer" }

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all.page(params[:page]).per(5)
  end

  # GET /artists/1 or /artists/1.json
  def show
    @albums = @artist.albums
    @songs = @artist.songs
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        if artist_params['avatar']
          url = CloudinaryService.upload_image(artist_params['avatar'])
          @artist.update(image: url)
        end
        
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        if artist_params['avatar']
          url = CloudinaryService.upload_image(artist_params['avatar'])
          @artist.update(image: url)
        end
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :description, :birthdate, :tag, :avatar)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="container-fluid">

<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

</div>

app/views/artists/index.html.erb
<div class="container-fluid"> <h1 class="mt-4">Artists</h1> </div>
<div class="container-fluid d-flex justify-content-end mb-3">
  <%= link_to 'New artist', new_artist_path, class: "btn btn-primary" %>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-lg list-group-flush list my-n4">
            <% @artists.each do |artist| %>
              <li class="list-group-item">
                <div class="row align-items-center d-flex">
                  <div class="col col-2">
                    <% if artist.image.present? %>
                      <%= link_to edit_artist_path(artist) do %>
                        <%= image_tag artist.image, alt: "image", size: "160x120" %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="col">
                    <h4 class="mb-1 name">
                      <%= link_to artist.name, artist_path(artist) %>
                    </h4>
                    <p class="card-text small text-body-secondary">
                      <%= artist.description %>
                    </p>

                  </div>
                  <div class="col-auto">
                    <%= link_to 'Show', artist_path(artist), class: "btn btn-sm btn-primary d-none d-md-inline-block" %>
                    <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-primary d-none d-md-inline-block" %>
                  </div>
                </div> 
              </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <%= paginate @artists, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/artists/new.html.erb
<div class="container-fluid">

<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

</div>

app/views/artists/show.html.erb
<div class="header">

<div class="container-fluid mt-3">
  <div class="header-body">
    <div class="row align-items-end">
      <div class="col">
        <h1 class="header-title">
          <%= @artist.name %>
          <%= link_to edit_artist_path(@artist) do %>
            <i class="mx-2 fa fa-edit"></i> 
          <% end %>
        </h1>
      </div>
    </div>
  </div> 
  <div class="row">
    <div class="col-12">  </div>
      <% if @artist.image.present? %>
        <%= link_to edit_artist_path(@artist) do %>
          <%= image_tag @artist.image, alt: "image", size: "485x325" %>
        <% end %>
      <% end %>

      <p class="mt-3">
        <h3>Description:</h3>
        <p><%= @artist.description %></p>
      </p>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <!-- Projects -->
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">
            Danh sách albums của <%=  @artist.name %>
          </h4>
          <%= link_to 'New album', new_album_path(artist_id: @artist.id), class: "btn btn-sm btn-primary" %>
        </div>
        <div class="table-responsive mb-0" data-list='{"valueNames": ["project-project", "project-status", "project-progress", "project-date"]}'>
          <table class="table table-sm table-nowrap card-table table-hover">
            <thead>
              <tr>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-project">
                    Logo
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-status">
                    Title
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-progress">
                    Create date
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort text-center" data-sort="project-date">
                    Number song 
                  </a>
                </th>
              </tr>
            </thead>
            <tbody class="list">
            <% @albums.each do |album| %>
              <tr>
                <td class="project-project">
                  <h4 class="fw-normal mb-1">
                    <% if album.image.present? %>
                      <%= link_to album_path(album) do %>
                        <%= image_tag album.image, alt: "image", size: "50x150" %>
                      <% end %>
                    <% end %>
                  </h4> 
                </td>
                <td class="project-status">
                  <%= link_to "#{album.title}", album_path(album) %>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= album.created_at&.strftime("%d/%m/%Y") %>
                  </div>
                </td>
                <td class="project-date">
                  <div class="d-flex mx-5">
                    <%= album.songs.size %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div> 
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <!-- Projects -->
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">
            Danh sách nhạc của <%=  @artist.name %>
          </h4>
        <%= link_to 'New song', new_song_path, class: "btn btn-sm btn-primary" %>
        </div>
        <div class="table-responsive mb-0" data-list='{"valueNames": ["project-project", "project-status", "project-progress", "project-date"]}'>
          <table class="table table-sm table-nowrap card-table table-hover">
            <thead>
              <tr>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-project">
                    Logo
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-status">
                    Title
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-progress">
                    View
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort text-center" data-sort="project-date">
                    Create date
                  </a>
                </th>
              </tr>
            </thead>
            <tbody class="list">
            <% @songs.each do |song| %>
              <tr>
                <td class="project-project">
                  <% if song.image.present? %>
                    <%= link_to song_path(song) do %>
                      <%= image_tag song.image, alt: "image",  size: "300x150" %>
                    <% end %>
                  <% end %>
                </td>
                <td class="project-status">
                  <%= link_to "#{song.title}", song_path(song) %>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= song.views %>
                  </div>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= song.created_at&.strftime("%d/%m/%Y") %>
                  </div>
                </td>

                <td class="project-project">
                  <h4 class="fw-normal mb-1">
                    <% if song.audio.present? %>
                      <audio controls>
                        <source src="<%= song.audio %>" type="audio/mpeg">
                      </audio>                   
                    <% end %>
                  </h4> 
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div> 
</div>