config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :singers
  resources :albums
  resources :artists
  resources :genres
  resources :clients, only: [:index]
  resources :payments, only: [:index] 
  resources :songs do
    member do
      get 'duration'
    end
  end
  devise_for :users
  root to: "dashboard#index"

  resources :dashboard, only: [:index] do 
    collection do
      get :client_chart
      get :payment_chart
      get :status_chart
    end 
  end
  namespace :api, defaults: { format: :json } do
    post 'login', to: 'auth#login'
    post 'google_oauth2', to: 'auth#google_oauth2'

    resources :singers, only: [:index, :show] do 
      collection do
        get 'albums'
      end
    end
    resources :genres, only: [:index, :show] do
      member do
        get :albums
        get :related
      end
    end
    resources :authors, only: [:index, :create, :show]
    resources :albums, only: [:index, :create, :show] do
      member do
        get :related
      end
    end
    resources :songs, only: [:index, :create, :show] do 
      resources :comments, only: [:index]
    end

    resources :comments, only: [:show]    

    namespace :me do
      resources :rooms, only: [:index, :create, :destroy] do
        member do
          get :songs
        end
      end

      resources :invitations, only: [:index, :create, :show]
      resources :suggest, only: [:index, :create]
      resources :albums, only: [:index, :create, :show, :destroy, :update] do
        member do
          post 'add_song_ids'
          post 'remove_song_ids'
          post :songs
        end
      end
      resources :histories, only: [:index, :create]
      resources :likes, only: [:index, :create] do
        collection do
          delete 'destroys'
        end
      end
      get 'search'
      resources :follows, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
    end

    resources :me, only: [:index]
    post '/create-checkout-session', to: 'payments#create_checkout_session'
    post '/create-checkout-submission', to: 'payments#create_checkout_submission'
    resources :stripe_webhooks, only: [:create]
  end

  match '*path', to: 'api/application#options', via: :options

end

app/models/album.rb
class Album < ApplicationRecord
  attr_accessor :song_ids, :logo

  belongs_to :artist, optional: true
  belongs_to :user, optional: true
  belongs_to :genre, optional: true

  has_many :album_songs, dependent: :destroy
  has_many :songs, through: :album_songs
  has_many :liked_albums, -> { where(tag: :like) }, class_name: 'HistoryLike'

  enum status: { favorite: "favorite", normal: "normal" }

  after_initialize :set_default_status, if: :new_record?

 private

  def set_default_status
    self.status ||= :normal
  end
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all.page(params[:page]).per(8)
  end

  # GET /albums/1 or /albums/1.json
  def show
    @songs = @album.songs.where(private: false)
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)
    respond_to do |format|
      if @album.save
        if album_params['logo']
          url = CloudinaryService.upload_image(album_params['logo'])
          @album.update(image: url)
        end
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        if album_params['logo']
          url = CloudinaryService.upload_image(album_params['logo'])
          @album.update(image: url)
        end
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description, :logo, :image, :genre_id, :artist_id)
    end
end

app/controllers/api/albums_controller.rb
class Api::AlbumsController < Api::ApplicationController
  def index
    page_size = params[:page_size] || 10
    albums = Album.where(artist_id: nil, user_id: nil).page(params[:page]).per(page_size)
    render json: {
      albums: ActiveModel::Serializer::CollectionSerializer.new(albums, each_serializer: AlbumSerializer,is_song: false),
      total_pages: albums.total_pages
    }
  end

  def show 
    albums = Album.find(params[:id])
    render json: albums, each_serializer: AlbumSerializer, is_song: true
  end

  def related
    album = Album.find(params[:id])
    if album && album.genre && album.genre.albums
      albums = album.genre.albums.where.not(id: album.id).limit(3)
      render json: albums, each_serializer: AlbumSerializer, is_song: false
    else
      render json: []
    end
  end
  
end

app/controllers/api/me/albums_controller.rb
class Api::Me::AlbumsController < Api::ApplicationController
  def index
    page_size = params[:page_size] || 10
    albums = @current_user.albums.page(params[:page]).per(page_size)
    if albums
      render json: {
        albums: ActiveModel::Serializer::CollectionSerializer.new(albums, each_serializer: AlbumSerializer,is_song: false),
        total_pages: albums.total_pages
      }
    else
      render json: {}, status: :ok
    end
  end

  def create
    @album = @current_user.albums.new(album_params)

    if @album.save
      if album_params['logo']
        url = CloudinaryService.upload_image(album_params['logo'])
        @album.update(image: url)
      end
      render json: @album, serializer: AlbumSerializer, is_song: false, status: :created
    else
      render json: { error: 'Không thể lưu album' }, status: :unprocessable_entity
    end
  end

  def update
    album = @current_user.albums.find(params[:id])
    if album && album_params['logo']
      url = CloudinaryService.upload_image(album_params['logo'])
      album.update(image: url)
      render json: album, serializer: AlbumSerializer, is_song: false, status: :created
    else
      render json: { error: 'Không thể  upload' }, status: :unprocessable_entity
    end
  end


  def add_song_ids
    album = @current_user.albums.find(params[:id])
    song_ids = JSON.parse(params[:song_ids]).uniq
  
    existing_song_ids = album.songs.pluck(:id)
    new_song_ids = song_ids - existing_song_ids
  
    if new_song_ids.present?
      if album.songs << Song.where(id: new_song_ids)
        render json: album, serializer: AlbumSerializer, is_song: true
      else
        render json: { success: false, error: "Không thể thêm các bài hát vào album" }, status: :unprocessable_entity
      end
    else
      render json: { success: false, error: "Không có bài hát mới để thêm vào album" }, status: :unprocessable_entity
    end
  end
  

  def remove_song_ids
    album = @current_user.albums.find(params[:id])
    song_ids = JSON.parse(params[:song_ids]).uniq
  
    songs = AlbumSong.where(song_id: song_ids) 
  
    if songs.destroy_all 
      render json: album, serializer: AlbumSerializer, is_song: true
    else
      render json: { success: false, error: "Không thể xóa các bài hát khỏi album" }, status: :unprocessable_entity
    end
  end
  
  def show 
    album = @current_user.albums.where(id: params[:id]).first
    if album
      render json: album, serializer: AlbumSerializer, is_song: true
    else
      render json: {}, status: :ok
    end
  end

  def destroy 
    album = @current_user.albums.find(params[:id])
    if album.destroy
      render json: {success: true, status: "Xóa thành công"}, status: :ok
    else
      render json: {success: true, error: "Có lỗi xảy ra"}, status: :unprocessable_entity
    end
  end

  def songs
    album = @current_user.albums.find(params[:id])
    song = album.songs.new(song_params)
    if song.save
      if song_params['logo'].present?
        url = CloudinaryService.upload_image(song_params['logo'])
      end
      if song_params['mp3_file'].present?
        audio = CloudinaryService.upload_mp3(song_params['mp3_file'])
      end
      song.update(image: url, audio: audio, private: true)
      render json: {success: true, status: "Thêm thành công"}, status: :ok
    else
      render json: {success: false, error: "Có lỗi xảy ra"}, status: :unprocessable_entity
    end
  end

  private

    def album_params
      params.permit(:title, :description, :logo, :song_ids)
    end

    def song_params
      params.permit(:title, :lyric, :release_date, :genre_id, :copyright, :mp3_file, :logo, album_ids: [], artist_ids: [])
    end
    
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<div class="row justify-content-center">
  <%= form_with(model: album) do |form| %>
    <% if album.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

        <ul>
          <% album.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-12 col-md-6">

        <div class="form-group">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control", required: true %>
        </div>

      </div>

      <div class="col-12">

        <div class="form-group">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_field :description, class: "form-control", required: true %>
        </div>

      </div>

      <div class="col-12 col-md-6">
        <div class="form-group">
          <%= form.label :logo, "Logo", class: "form-label" %>
          <%= form.file_field :logo, class: "form-control" %>
        </div>
      </div>

      <% if params[:genre_id].present? %>
        <%= form.hidden_field :genre_id, value: params[:genre_id] %>
      <% else %>
        <div class="col-12 col-md-6">
          <div class="form-group">
            <%= form.label :genre_id, "Genre", class: "form-label" %>
            <%= form.select :genre_id, options_for_select(Genre.all.map { |genre| [genre.title, genre.id] }, album.genre_id ), { include_blank: "Select Genre" }, class: "form-control", required: true %>
          </div>
        </div>
      <% end %>

      <% if params[:artist_id].present? %>
        <%= form.hidden_field :artist_id, value: params[:artist_id] %>
      <% else %>
        <div class="col-12 col-md-6">
          <div class="form-group">
            <%= form.label :artist_id, "Genre", class: "form-label" %>
            <%= form.select :artist_id, options_for_select(Artist.all.map { |artist| [artist.name, artist.id] }, album.artist_id ), { include_blank: "Select Artist" }, class: "form-control", required: true %>
          </div>
        </div>
      <% end %>
    
    </div>
    <div class="actions mb-3">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/albums/edit.html.erb
<div class="container-fluid">
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>
</div>

app/views/albums/index.html.erb
<div class="container-fluid"> <h1 class="mt-4">Albums</h1> </div>
<div class="container-fluid d-flex justify-content-end mb-3">
  <%= link_to 'New album', new_album_path, class: "btn btn-primary" %>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-lg list-group-flush list my-n4">
            <% @albums.each do |album| %>
              <li class="list-group-item">
                <div class="row align-items-center">
                  <div class="col col-2">
                    <% if album.image.present? %>
                      <%= link_to edit_album_path(album) do %>
                        <%= image_tag album.image, alt: "image", size: "160x120" %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="col">
                    <h4 class="mb-1 name">
                      <%= link_to album.title, album_path(album) %>
                    </h4>
                    <p class="card-text small text-body-secondary">
                      <%= album.description %>
                    </p>

                  </div>
                  <div class="col-auto">
                    <%= link_to 'Show', album_path(album), class: "btn btn-sm btn-primary d-none d-md-inline-block" %>
                    <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-primary d-none d-md-inline-block" %>
                  </div>
                </div> 
              </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <%= paginate @albums, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/albums/new.html.erb
<div class="container-fluid">
  <h1>New Album</h1>

  <%= render 'form', album: @album %>

  <%= link_to 'Back', albums_path %>
</div>

app/views/albums/show.html.erb
<div class="header">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-end">
        <div class="col">
          <h1 class="header-title">
            <%= @album.title %>
            <%= link_to edit_album_path(@album) do %>
              <i class="mx-2 fa fa-edit"></i> 
            <% end %>
          </h1>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="col-12">  </div>
      <% if @album.image.present? %>
        <%= link_to edit_album_path(@album) do %>
          <%= image_tag @album.image, alt: "image", size: "485x325" %>
        <% end %>
      <% end %>

      <p class="mt-3">
        <h3>Description:</h3>
        <p><%= @album.description %></p>
      </p>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <!-- Projects -->
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">
            Danh sách nhạc của <%= @album.title %>
          </h4>
          <%= link_to 'New song', new_song_path(album_id: @album.id), class: "btn btn-sm btn-primary" %>
        </div>
        <div class="table-responsive mb-0" data-list='{"valueNames": ["project-project", "project-status", "project-progress", "project-date"]}'>
          <table class="table table-sm table-nowrap card-table table-hover">
            <thead>
              <tr>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-project">
                    Logo
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-status">
                    Title
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort" data-sort="project-progress">
                    View
                  </a>
                </th>
                <th>
                  <a href="#" class="text-body-secondary list-sort text-center" data-sort="project-date">
                    Create date
                  </a>
                </th>
              </tr>
            </thead>
            <tbody class="list">
            <% @songs.each do |song| %>
              <tr>
                <td class="project-project">
                  <% if song.image.present? %>
                    <%= link_to song_path(song) do %>
                      <%= image_tag song.image, alt: "image",  size: "300x150" %>
                    <% end %>
                  <% end %>
                </td>
                <td class="project-status">
                  <%= link_to "#{song.title}", song_path(song) %>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= song.views %>
                  </div>
                </td>
                <td class="project-progress">
                  <div class="d-flex align-items-center">
                    <%= song.created_at&.strftime("%d/%m/%Y") %>
                  </div>
                </td>

                <td class="project-project">
                  <h4 class="fw-normal mb-1">
                    <% if song.audio.present? %>
                      <audio controls>
                        <source src="<%= song.audio %>" type="audio/mpeg">
                      </audio>                   
                    <% end %>
                  </h4> 
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div> 
</div>