config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :singers
  resources :albums
  resources :artists
  resources :genres
  resources :clients, only: [:index]
  resources :payments, only: [:index] 
  resources :songs do
    member do
      get 'duration'
    end
  end
  devise_for :users
  root to: "dashboard#index"

  resources :dashboard, only: [:index] do 
    collection do
      get :client_chart
      get :payment_chart
      get :status_chart
    end 
  end
  namespace :api, defaults: { format: :json } do
    post 'login', to: 'auth#login'
    post 'google_oauth2', to: 'auth#google_oauth2'

    resources :singers, only: [:index, :show] do 
      collection do
        get 'albums'
      end
    end
    resources :genres, only: [:index, :show] do
      member do
        get :albums
        get :related
      end
    end
    resources :authors, only: [:index, :create, :show]
    resources :albums, only: [:index, :create, :show] do
      member do
        get :related
      end
    end
    resources :songs, only: [:index, :create, :show] do 
      resources :comments, only: [:index]
    end

    resources :comments, only: [:show]    

    namespace :me do
      resources :rooms, only: [:index, :create, :destroy] do
        member do
          get :songs
        end
      end

      resources :invitations, only: [:index, :create, :show]
      resources :suggest, only: [:index, :create]
      resources :albums, only: [:index, :create, :show, :destroy, :update] do
        member do
          post 'add_song_ids'
          post 'remove_song_ids'
          post :songs
        end
      end
      resources :histories, only: [:index, :create]
      resources :likes, only: [:index, :create] do
        collection do
          delete 'destroys'
        end
      end
      get 'search'
      resources :follows, only: [:index, :create, :destroy]
      resources :comments, only: [:create, :destroy, :show]
    end

    resources :me, only: [:index]
    post '/create-checkout-session', to: 'payments#create_checkout_session'
    post '/create-checkout-submission', to: 'payments#create_checkout_submission'
    resources :stripe_webhooks, only: [:create]
  end

  match '*path', to: 'api/application#options', via: :options

end

app/views/layouts/_sidebar.html.erb
<nav class="navbar navbar-vertical fixed-start navbar-expand-md navbar-dark" id="sidebar">
  <div class="container-fluid">

    <!-- Toggler -->
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Brand -->
    <%= link_to image_tag("logo.svg", class: "navbar-brand-img mx-auto"), '/',  data: {turbolinks: false}, class: "navbar-brand" %>

    <!-- User (xs) -->
    <div class="navbar-user d-md-none">

      <!-- Dropdown -->
      <div class="dropdown">

        <!-- Toggle -->
        <a href="#" id="sidebarIcon" class="dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="avatar avatar-sm avatar-online">
          </div>
        </a>

        <!-- Menu -->

      </div>

    </div>

    <!-- Collapse -->
    <div class="navbar-collapse collapse" id="sidebarCollapse" style="">

      <!-- Form -->
      <form class="mt-4 mb-3 d-md-none">
        <div class="input-group input-group-rounded input-group-merge input-group-reverse">
          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-text">
            <span class="fe fe-search"></span>
          </div>
        </div>
      </form>

      <!-- Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to '/', class: "nav-link active", data: {turbolinks: false} do %>
            <i class="fe fe-home"></i> Dashboard
          <% end %>
        </li>
        <li class="nav-item" role="button">
          <%= link_to albums_path, class: "nav-link active" do %>
            <i class="fa fa-regular fa-building"></i> Albums
          <% end %>
        </li>
        <li class="nav-item" role="button">
          <%= link_to genres_path, class: "nav-link active" do %>
            <i class="fa fa-regular fa-calendar"></i> Genres
          <% end %>
        </li>
        <li class="nav-item" role="button">
          <%= link_to artists_path, class: "nav-link active" do %>
            <i class="fa fa-regular fa-calendar"></i> Artists
          <% end %>
        </li>
        <li class="nav-item" role="button">
          <%= link_to songs_path, class: "nav-link active" do %>
            <i class="fa fa-regular fa-calendar"></i> Songs
          <% end %>
        </li>
        <li class="nav-item" role="button">
          <%= link_to payments_path, class: "nav-link active" do %>
            <i class="fe fe-user"></i> Payments
          <% end %>
        </li>
        <li class="nav-item" role="button">
          <%= link_to clients_path, class: "nav-link active" do %>
            <i class="fe fe-user"></i> User
          <% end %>
        </li>
      </ul>
      
      <!-- Push content down -->
      <div class="mt-auto">
        <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-primary w-100" do %>
          <i class="fa fa-sign-out-alt"></i> Sign out
        <% end %>
      </div>

     
    </div> 
  
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= favicon_link_tag asset_path("favicon.png") %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Referrer" content="origin">
    <meta name="facebook-domain-verification" content="" />

    <!-- Open Graph Params -->
    <meta property="og:url" content="">
    <meta property="og:type" content="website">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:site_name" content="">
    <meta property="og:locale" content="en_ie">
    <meta property="og:image" content="">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="">
    <meta name="twitter:description" content="">
    <meta name="twitter:image" content="">

    <title>Music - Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="https://kit.fontawesome.com/44b3d57b9a.js" crossorigin="anonymous"></script>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>

    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />

    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main id="content" role="main" class="main">
      <%= render "admin/shared/sidebar" %>
      <div class="main-content" style="padding-top: 12px;">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>
      </div>
    </main>

  </body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= favicon_link_tag asset_path("favicon.png") %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Referrer" content="origin">
    <meta name="facebook-domain-verification" content="" />

    <!-- Open Graph Params -->
    <meta property="og:url" content="">
    <meta property="og:type" content="website">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:site_name" content="">
    <meta property="og:locale" content="en_ie">
    <meta property="og:image" content="">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="">
    <meta name="twitter:description" content="">
    <meta name="twitter:image" content="">

    <title>Music - Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="https://kit.fontawesome.com/44b3d57b9a.js" crossorigin="anonymous"></script>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>

    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />

    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main id="content" role="main" class="main">
      <%= render "layouts/sidebar" %>
      <div class="main-content" style="padding-top: 12px;">
        <%# <div class="container-fluid"> %>
          <% if notice.present? || alert.present? %>
            <p class="notice d-block text-center" style="background-color: <%= alert.present? ? 'red' : 'mediumspringgreen' %>;">
              <%= alert.present? ? alert : notice %>
            </p>
          <% end %>
          <%= yield %>
        <%# </div> %>
      </div>
    </main>

  </body>
</html>